apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-demo-app-monitor
  namespace: monitoring
  labels:
    release: prometheus   # Must match Helm release name
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: devops-demo-app
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
